void InComm_Stop(void){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	GPIOC->MODER &= ~GPIO_MODER_MODER0_Msk;
	GPIOC->MODER |= (0x00 << GPIO_MODER_MODER0_Pos);
	GPIOC->PUPDR &= ~GPIO_PUPDR_PUPD0;

	SYSCFG->EXTICR[0] &= ~ SYSCFG_EXTICR1_EXTI0_Msk;
	SYSCFG->EXTICR[0] |=   SYSCFG_EXTICR1_EXTI0_PC;

	EXTI->IMR |= EXTI_IMR_IM0;

	EXTI->RTSR |= EXTI_RTSR_TR0;
	EXTI->FTSR &= ~EXTI_FTSR_TR0;
	// EXTI->RTSR &= ~EXTI_RTSR_TR0;
	// EXTI->FTSR |= EXTI_FTSR_TR0;
}

void InComm_Start(void){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;

	GPIOC->MODER &= ~GPIO_MODER_MODER1_Msk;
	GPIOC->MODER |= (0x00 << GPIO_MODER_MODER1_Pos);
	GPIOC->PUPDR &= ~GPIO_PUPDR_PUPD1;

	SYSCFG->EXTICR[0] &= ~ SYSCFG_EXTICR1_EXTI1_Msk;
	SYSCFG->EXTICR[0] |=   SYSCFG_EXTICR1_EXTI1_PC;

	EXTI->IMR |= EXTI_IMR_IM1;
	EXTI->RTSR |= EXTI_RTSR_TR1;
	EXTI->FTSR &= ~EXTI_FTSR_TR1;
	// EXTI->RTSR &= ~EXTI_RTSR_TR1;
	// EXTI->FTSR |= EXTI_FTSR_TR1;
}


NVIC_SetPriority(EXTI0_IRQn, 1);
NVIC_SetPriority(EXTI1_IRQn, 1);
NVIC_EnableIRQ(EXTI0_IRQn);
NVIC_EnableIRQ(EXTI1_IRQn);

void EXTI0_IRQHandler(){
	if ((EXTI->PR & EXTI_PR_PR0_Msk) != 0){
		EXTI->PR |= EXTI_PR_PR0;
	}
}

/*	RIGHT LIMIT SWITCH	*/
void EXTI1_IRQHandler(){
	if ((EXTI->PR & EXTI_PR_PR1_Msk) != 0){
		EXTI->PR |= EXTI_PR_PR1;

	}
}